#ifndef ELEKTRON_ESCORT_DEFAULTVALUES_H
#define ELEKTRON_ESCORT_DEFAULTVALUES_H

#define DEFAULT_MAIN_LOOP_RATE 30
#define DEFAULT_MAX_USERS 10
#define DEFAULT_POSE_COOLDOWN_TIME 3

#endif //ELEKTRON_ESCORT_DEFAULTVALUES_H
